version: "3.8"

services:
    etuutt_bot:
        build: .
        image: ungdev/etuutt-discord-bot
        env_file: .env
        ports:
            - "3000:3000"
        volumes:
            - logs:/usr/src/etuutt/logs

volumes:
    logs:
